theme: jekyll-theme-minimal
title: OSM Hackfest 2022
description: "A series of events across colleges in Nepal to share the knowledge of Open Technologies and grow the network of contributors.<br/><br/>
<h2>By:</h2>
<ul>
<li>Open Mapping Hub - Asia Pacific</li>
<li>Open Knowledge Nepal</li>
<li>Kathmandu Living Labs</li>
<li>FOSS Community</li>
</ul>"
